apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-ir-aci
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.imageRecognizer.replicaCount.aci }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}-ir-aci
    spec:
      containers:
        - name: {{ include "fullname" . }}-ir-aci
          image: "{{ .Values.imageRecognizer.image.repository }}:{{ .Values.imageRecognizer.image.tag }}"
          imagePullPolicy: "{{ .Values.imageRecognizer.image.pullPolicy }}"
          env:
          - name: IP_JOB_SERVER
            value: "{{ index .Values.backend.ingress.hosts 0 }}"
          - name: AZURE_BLOB_ACCOUNT
            value: "{{ .Values.imageRecognizer.azureBlob.storageAccount }}"
          - name: AZURE_BLOB_KEY
            value: "{{ .Values.imageRecognizer.azureBlob.key }}"          
          #resources:
          #  requests:
          #    memory: "{{ .Values.imageRecognizer.resources.requests.memory }}"
          #    cpu: "{{ .Values.imageRecognizer.resources.requests.cpu }}"
          #  limits:
          #    memory: "{{ .Values.imageRecognizer.resources.limits.memory }}"
          #    cpu: "{{ .Values.imageRecognizer.resources.limits.cpu }}"
      dnsPolicy: ClusterFirst
      nodeName: aci-connector
