apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-ir
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.imageRecognizerCluster.replicas }}
  template:
    metadata:
      labels:
        app: facial-recognition
    spec:
      containers:
        - name: facial-recognition
          image: {{ default "rbitia/facialRecognitionDemo:latest" .Values.imageRecognizerCluster.image }}
          imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      # Tolerate the ACI taint to get the scheduler to schedule it.
